# Generated by Django 3.0.8 on 2020-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200725_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vil_post', models.ManyToManyField(related_name='post_vil', to='posts.Post')),
            ],
        ),
    ]
