# Generated by Django 3.0.8 on 2020-07-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_vil_vil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vil',
            name='vil_post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_vil',
            field=models.ManyToManyField(related_name='vil_post', to='posts.Vil'),
        ),
    ]
