# Generated by Django 3.0.8 on 2020-07-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200729_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_vil',
        ),
        migrations.DeleteModel(
            name='Vil',
        ),
    ]
