# Generated by Django 3.0.8 on 2020-08-04 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=20, null=True, unique=True)),
                ('gender', models.CharField(choices=[('man', '남성'), ('woman', '여성'), ('human', '선택하지 않음')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(max_length=300, null=True)),
                ('main_village', models.CharField(max_length=10, null=True)),
                ('second_village', models.CharField(blank=True, max_length=10)),
                ('third_village', models.CharField(blank=True, max_length=10)),
                ('interest_tag1', models.CharField(blank=True, max_length=15)),
                ('interest_tag2', models.CharField(blank=True, max_length=15)),
                ('interest_tag3', models.CharField(blank=True, max_length=15)),
                ('follow', models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
