# Generated by Django 3.0.8 on 2020-08-02 19:31

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(max_length=300, null=True)),
                ('main_village', models.CharField(max_length=10, null=True)),
                ('second_village', models.CharField(blank=True, max_length=10)),
                ('third_village', models.CharField(blank=True, max_length=10)),
                ('interest_tag1', models.CharField(blank=True, max_length=15)),
                ('interest_tag2', models.CharField(blank=True, max_length=15)),
                ('interest_tag3', models.CharField(blank=True, max_length=15)),
                ('follow', models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('user', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
