# Generated by Django 3.0.8 on 2020-08-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200803_0431'),
        ('accounts', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, related_name='tags_in_userprofile', to='posts.Tag'),
        ),
    ]
