# Generated by Django 3.0.8 on 2020-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200729_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='introduce',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
