# Generated by Django 3.0.8 on 2020-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200731_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='introduce',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
